package main

import (
	"encoding/json"
	"fmt"
	"log"
)

type AutoGenerated []struct {
	AssertionID string `json:"assertionId"`
	Proofs      []struct {
		Triple     string `json:"triple"`
		TripleHash string `json:"tripleHash"`
		Proof      []struct {
			Right string `json:"right,omitempty"`
			Left  string `json:"left,omitempty"`
		} `json:"proof"`
	} `json:"proofs"`
}

var j = `[
     {
          "assertionId": "ab2b72b83c91b42c5f56c6f84fea4e8eec20f51c6fb19475d45f48988e2b8d2e",
          "proofs": [
               {
                    "triple": "<did:dkg:ab2b72b83c91b42c5f56c6f84fea4e8eec20f51c6fb19475d45f48988e2b8d2e> <http://schema.org/hasType> \"default\" .",
                    "tripleHash": "122945702b4b5000b435181ab6a6ad34ebf54f0a15855bd0d66b604742d16624",
                    "proof": [
                         {
                              "right": "9d87a1f518c52165c2b0b85972f770310a6ecd601b871a0dbe7b9251074b08f9"
                         },
                         {
                              "right": "e82af8f585d77d3deb344ffa1248b52d5be73ed3a791c1775e956cd10557eb8a"
                         },
                         {
                              "right": "f03bd9f6bda71f424752b9ff3961c69b14657cf53892c4eba5523e01060da1a6"
                         },
                         {
                              "left": "6787678c1e4bd4279c5979fb47025478b1272d98238b5a02470cf7dc90b9c4db"
                         },
                         {
                              "right": "4a3349ef00b2a46ca69224ec7916ef9734ba8fdf8a8c49b322946f125873e51"
                         },
                         {
                              "right": "98dba653dba5a3d00745af9ba5f5419481b3601f922f828be4eef487fe5c7aa1"
                         }
                    ]
               }
          ]
     }
]`

func main() {

	var out AutoGenerated
	err := json.Unmarshal([]byte(j), &out)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(out[0].AssertionID)
}
